#!/usr/bin/env bash
# Setup read-only accounts for MCP servers (database + Redis).
# Run once after fresh deployment, or to reset credentials.
#
# Usage:
#   bash scripts/setup_mcp_readonly.sh
#
# Prerequisites: .env must exist with POSTGRES_PASSWORD and REDIS_PASSWORD set.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$ROOT_DIR/.env"

if [ ! -f "$ENV_FILE" ]; then
    echo "ERROR: $ENV_FILE not found" >&2
    exit 1
fi

# Source .env
set -a
# shellcheck source=/dev/null
. "$ENV_FILE"
set +a

DB_HOST="${DB_HOST:-localhost}"
DB_PORT="${DB_PORT:-5432}"
REDIS_HOST="${REDIS_HOST:-localhost}"
REDIS_PORT="${REDIS_PORT:-6379}"

# -- Generate passwords -------------------------------------------------------
DB_RO_PASSWORD=$(python3 -c "import secrets,base64;print(base64.urlsafe_b64encode(secrets.token_bytes(24)).decode().rstrip('='))")
REDIS_RO_PASSWORD=$(python3 -c "import secrets,base64;print(base64.urlsafe_b64encode(secrets.token_bytes(16)).decode().rstrip('='))")

echo "=== Setting up MCP read-only accounts ==="

# -- PostgreSQL ----------------------------------------------------------------
echo ""
echo "--- PostgreSQL: creating claude_readonly user ---"
PGPASSWORD="${POSTGRES_PASSWORD}" psql -h "$DB_HOST" -p "$DB_PORT" -U "${POSTGRES_USER:-postgres}" -d "${POSTGRES_DB:-dotmac_omni}" <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'claude_readonly') THEN
        CREATE ROLE claude_readonly LOGIN PASSWORD '${DB_RO_PASSWORD}';
    ELSE
        ALTER ROLE claude_readonly PASSWORD '${DB_RO_PASSWORD}';
    END IF;
END
\$\$;

GRANT CONNECT ON DATABASE ${POSTGRES_DB:-dotmac_omni} TO claude_readonly;
GRANT USAGE ON SCHEMA public TO claude_readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO claude_readonly;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO claude_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO claude_readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO claude_readonly;
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public FROM claude_readonly;
SQL
echo "  [OK] PostgreSQL claude_readonly user created"

# -- Redis MCP credentials -----------------------------------------------------
echo ""
echo "--- Redis: generating MCP read-only credentials ---"
echo "  [OK] Redis MCP credentials generated"
echo "  [INFO] Restart Redis so runtime ACL picks up updated env: docker compose restart redis"

# -- Update .env ---------------------------------------------------------------
echo ""
echo "--- Updating .env with MCP credentials ---"

# Remove old MCP lines if present
sed -i '/^DOTMAC_OMNI_DB_DSN=/d' "$ENV_FILE"
sed -i '/^MCP_REDIS_USERNAME=/d' "$ENV_FILE"
sed -i '/^MCP_REDIS_PASSWORD=/d' "$ENV_FILE"

# Append new ones
cat >> "$ENV_FILE" <<EOF

# MCP read-only credentials (auto-generated by setup_mcp_readonly.sh)
DOTMAC_OMNI_DB_DSN=postgresql://claude_readonly:${DB_RO_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB:-dotmac_omni}
MCP_REDIS_USERNAME=claude_readonly
MCP_REDIS_PASSWORD=${REDIS_RO_PASSWORD}
EOF
echo "  [OK] .env updated"

# -- Verify --------------------------------------------------------------------
echo ""
echo "--- Verifying DB read-only access ---"
PGPASSWORD="${DB_RO_PASSWORD}" psql -h "$DB_HOST" -p "$DB_PORT" -U claude_readonly -d "${POSTGRES_DB:-dotmac_omni}" \
    -c "SELECT COUNT(*) AS people_count FROM people;" -t 2>&1 | xargs
echo "  [OK] DB read verified"

echo ""
echo "--- Verifying Redis read-only access ---"
docker exec dotmac_omni_redis redis-cli --user claude_readonly -a "${REDIS_RO_PASSWORD}" --no-auth-warning PING
echo "  [OK] Redis read verified"

echo ""
echo "=== All MCP read-only accounts configured ==="
echo ""
echo "Next steps:"
echo "  1. Restart Claude Code to pick up the new MCP servers"
echo "  2. Run: python scripts/generate_schema_skill.py   (to regenerate schema reference)"
echo "  3. Run: python scripts/check_mcp_db.py            (to verify everything)"
