"""DotMac ERP integration service for syncing with erp.dotmac.io."""

from app.services.dotmac_erp.agent_sync import (
    AgentSyncResult,
    DotMacERPAgentSync,
    dotmac_erp_agent_sync,
)
from app.services.dotmac_erp.client import (
    DotMacERPAuthError,
    DotMacERPClient,
    DotMacERPError,
    DotMacERPNotFoundError,
    DotMacERPRateLimitError,
    DotMacERPTransientError,
)
from app.services.dotmac_erp.contact_sync import (
    ContactSyncResult,
    DotMacERPContactSync,
    dotmac_erp_contact_sync,
)
from app.services.dotmac_erp.inventory_sync import (
    DotMacERPInventorySync,
    InventorySyncResult,
    dotmac_erp_inventory_sync,
)
from app.services.dotmac_erp.material_request_sync import (
    DotMacERPMaterialRequestSync,
    MaterialRequestSyncResult,
    dotmac_erp_material_request_sync,
)
from app.services.dotmac_erp.shift_sync import (
    DotMacERPShiftSync,
    ShiftSyncResult,
    dotmac_erp_shift_sync,
)
from app.services.dotmac_erp.stats import (
    get_agent_sync_history,
    get_contact_sync_history,
    get_daily_stats,
    get_inventory_sync_history,
    get_last_agent_sync,
    get_last_contact_sync,
    get_last_inventory_sync,
    get_last_material_request_sync,
    get_last_shift_sync,
    get_last_sync,
    get_last_team_sync,
    get_material_request_sync_history,
    get_shift_sync_history,
    get_sync_history,
    get_team_sync_history,
    record_agent_sync_result,
    record_contact_sync_result,
    record_inventory_sync_result,
    record_material_request_sync_result,
    record_shift_sync_result,
    record_sync_result,
    record_team_sync_result,
)
from app.services.dotmac_erp.sync import DotMacERPSync, SyncResult, dotmac_erp_sync
from app.services.dotmac_erp.team_sync import (
    DotMacERPTeamSync,
    TeamSyncResult,
    dotmac_erp_team_sync,
)
from app.services.dotmac_erp.technician_sync import (
    DotMacERPTechnicianSync,
    TechnicianSyncResult,
    dotmac_erp_technician_sync,
)

__all__ = [
    "AgentSyncResult",
    "ContactSyncResult",
    "DotMacERPAgentSync",
    "DotMacERPAuthError",
    "DotMacERPClient",
    "DotMacERPContactSync",
    "DotMacERPError",
    "DotMacERPInventorySync",
    "DotMacERPMaterialRequestSync",
    "DotMacERPNotFoundError",
    "DotMacERPRateLimitError",
    "DotMacERPShiftSync",
    "DotMacERPSync",
    "DotMacERPTeamSync",
    "DotMacERPTechnicianSync",
    "DotMacERPTransientError",
    "InventorySyncResult",
    "MaterialRequestSyncResult",
    "ShiftSyncResult",
    "SyncResult",
    "TeamSyncResult",
    "TechnicianSyncResult",
    "dotmac_erp_agent_sync",
    "dotmac_erp_contact_sync",
    "dotmac_erp_inventory_sync",
    "dotmac_erp_material_request_sync",
    "dotmac_erp_shift_sync",
    "dotmac_erp_sync",
    "dotmac_erp_team_sync",
    "dotmac_erp_technician_sync",
    "get_agent_sync_history",
    "get_contact_sync_history",
    "get_daily_stats",
    "get_inventory_sync_history",
    "get_last_agent_sync",
    "get_last_contact_sync",
    "get_last_inventory_sync",
    "get_last_material_request_sync",
    "get_last_shift_sync",
    "get_last_sync",
    "get_last_team_sync",
    "get_material_request_sync_history",
    "get_shift_sync_history",
    "get_sync_history",
    "get_team_sync_history",
    "record_agent_sync_result",
    "record_contact_sync_result",
    "record_inventory_sync_result",
    "record_material_request_sync_result",
    "record_shift_sync_result",
    "record_sync_result",
    "record_team_sync_result",
]
